### ISSUE TITLE
Block indent affects list indent

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-indent#13]
Indenting a block should not affect what happens if you turn that block into a list item after that. Those things (block indentation and list indentation) are, IMO, separate features. In fact, I don't even know how it happens right now that one turns into another. I suspected using the same attribute, but lists use `listIndent` and block indent uses `blockIndent`. 

![Jul-16-2019 13-35-41](https://user-images.githubusercontent.com/156149/61291392-b39ca580-a7ce-11e9-80db-7f23edbadcdb.gif)

**Comment by jodator** [comment]
AFAICS it is the case that `blockIndent` attribute is not removed when `<paragraph>` is converted to `<listItem`>:

![Peek 2019-07-16 13-48](https://user-images.githubusercontent.com/247363/61292024-71746380-a7d0-11e9-9df8-2dc4cec00ac6.gif)

**Comment by Reinmar** [comment]
OMG, my bad. I thought that this second item becomes a sublist. But it's a separate item with a margin. I should've checked the view structure.

Anyway, this is https://github.com/ckeditor/ckeditor5-engine/issues/1228 again.
